# -*- coding: utf-8 -*-
"""Decodelab.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1dQnccMMGtWmYdxyFO9WoEiU9ccB8eqLW
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
df = pd.read_csv("/content/sample_data/Dataset for Data Analytics.csv")
df.head()

from google.colab import drive
drive.mount('/content/drive')

print("Rows and Columns:", df.shape)

df.info()

df.describe()

df.isnull().sum()

df.duplicated().sum()

missing_percent = (df.isnull().sum() / len(df)) * 100
missing_percent = missing_percent.sort_values(ascending=False)
print(missing_percent)

print(missing_percent)

!pip install scikit-learn

from sklearn.impute import KNNImputer

numeric_columns = df.select_dtypes(include=['int64', 'float64']).columns

imputer = KNNImputer(n_neighbors=5)

df[numeric_columns] = imputer.fit_transform(df[numeric_columns])

df.isnull().sum()

df["CouponCode"] = df["CouponCode"].fillna(df["CouponCode"].mode()[0])

df.isnull().sum()

Q1 = df["TotalPrice"].quantile(0.25)
Q3 = df["TotalPrice"].quantile(0.75)

IQR = Q3 - Q1

lower_bound = Q1 - 1.5 * IQR
upper_bound = Q3 + 1.5 * IQR

outliers = df[(df["TotalPrice"] < lower_bound) | (df["TotalPrice"] > upper_bound)]

print("Number of Outliers:", len(outliers))

df = df[(df["TotalPrice"] >= lower_bound) & (df["TotalPrice"] <= upper_bound)]

print("New Dataset Shape:", df.shape)

Q1 = df["TotalPrice"].quantile(0.25)
Q3 = df["TotalPrice"].quantile(0.75)
IQR = Q3 - Q1

lower_bound = Q1 - 1.5 * IQR
upper_bound = Q3 + 1.5 * IQR

outliers = df[(df["TotalPrice"] < lower_bound) | (df["TotalPrice"] > upper_bound)]

print("Remaining Outliers:", len(outliers))

df["RevenuePerItem"] = df["TotalPrice"] / df["Quantity"]

df[["TotalPrice", "Quantity", "RevenuePerItem"]].head()



df["DiscountApplied"] = df["CouponCode"].apply(lambda x: "Yes" if pd.notna(x) else "No")

df[["CouponCode", "DiscountApplied"]].head()

df["Date"] = pd.to_datetime(df["Date"])

df["OrderYear"] = df["Date"].dt.year

df[["Date", "OrderYear"]].head()

print(df.columns)

df.to_csv("Cleaned_Dataset.csv", index=False)
print("Dataset saved successfully!")

import matplotlib.pyplot as plt

plt.figure(figsize=(8,5))
plt.hist(df["TotalPrice"], bins=20)
plt.title("Distribution of Total Price")
plt.xlabel("Total Price")
plt.ylabel("Frequency")
plt.show()

import seaborn as sns

plt.figure(figsize=(8,5))
sns.countplot(x="OrderStatus", data=df)
plt.title("Order Status Distribution")
plt.xticks(rotation=45)
plt.show()

plt.figure(figsize=(8,5))
sns.countplot(x="PaymentMethod", data=df)
plt.title("Payment Method Distribution")
plt.xticks(rotation=45)
plt.show()

import numpy as np
import pandas as pd
df["Vectorized_Total"] = df["Quantity"] * df["UnitPrice"]

df[["Quantity","UnitPrice","Vectorized_Total"]].head()

from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()

df["OrderStatus_Label"] = le.fit_transform(df["OrderStatus"])

df[["OrderStatus","OrderStatus_Label"]].head()

payment_encoded = pd.get_dummies(df["PaymentMethod"], prefix="Payment")

payment_encoded.head()

df = pd.concat([df, payment_encoded], axis=1)

corr_matrix = df.select_dtypes(include=["int64","float64"]).corr()

corr_matrix

import seaborn as sns
import matplotlib.pyplot as plt

plt.figure(figsize=(12,8))
sns.heatmap(corr_matrix, annot=True, cmap="coolwarm")
plt.title("Correlation Matrix")
plt.show()

upper = corr_matrix.where(np.triu(np.ones(corr_matrix.shape), k=1).astype(bool))

high_corr = [column for column in upper.columns if any(upper[column] > 0.80)]

print(high_corr)

print(corr_matrix["TotalPrice"].sort_values(ascending=False))

!pip install pandera
import pandera.pandas as pa
from pandera import Column, DataFrameSchema

schema = DataFrameSchema({
      "Quantity": Column(int),
          "UnitPrice": Column(float),
              "TotalPrice": Column(float),
                  "ItemsInCart": Column(int),
                  })
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

columns = ["Quantity","UnitPrice","ItemsInCart","TotalPrice"]

df[columns] = scaler.fit_transform(df[columns])

df.head()

feature_store = df[[
      "Quantity",
          "UnitPrice",
              "ItemsInCart",
                  "RevenuePerItem",
                      "OrderYear",
                          "DiscountApplied"
                          ]]

feature_store.head()

feature_store.to_csv("Central_Feature_Store.csv", index=False)

print("Central Feature Store Created Successfully!")

df = df.sort_values("Date")

df.head()

print("Stage 1 : INPUT ✓")
print("Stage 2 : PROCESS ✓")
print("Stage 3 : OUTPUT ✓")

print("Enterprise Data Pipeline Completed Successfully!")

# Commented out IPython magic to ensure Python compatibility.
# %whos

df.to_csv("Cleaned_Dataset.csv", index=False)

df = pd.read_csv("/content/sample_data/Dataset for Data Analytics.csv")

from google.colab import files
files.download("Cleaned_Dataset.csv")
